// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBADRDC1h04nIGDFkA9_i5oMoZhVSmJUac',
    appId: '1:525869975686:web:da103ddf118740a244a907',
    messagingSenderId: '525869975686',
    projectId: 'flutterapplic-c99bc',
    authDomain: 'flutterapplic-c99bc.firebaseapp.com',
    storageBucket: 'flutterapplic-c99bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ri9dNgLo_YCfhN5TdAs6VGva_wXrgW4',
    appId: '1:525869975686:android:7a4e3429fd5cabf644a907',
    messagingSenderId: '525869975686',
    projectId: 'flutterapplic-c99bc',
    storageBucket: 'flutterapplic-c99bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX29tz2gIVRkPvGeS1R6xvhkSWTXqIyIw',
    appId: '1:525869975686:ios:13a16c71cc75a27244a907',
    messagingSenderId: '525869975686',
    projectId: 'flutterapplic-c99bc',
    storageBucket: 'flutterapplic-c99bc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication19',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX29tz2gIVRkPvGeS1R6xvhkSWTXqIyIw',
    appId: '1:525869975686:ios:13a16c71cc75a27244a907',
    messagingSenderId: '525869975686',
    projectId: 'flutterapplic-c99bc',
    storageBucket: 'flutterapplic-c99bc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication19',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBADRDC1h04nIGDFkA9_i5oMoZhVSmJUac',
    appId: '1:525869975686:web:f2e96e522e303bd144a907',
    messagingSenderId: '525869975686',
    projectId: 'flutterapplic-c99bc',
    authDomain: 'flutterapplic-c99bc.firebaseapp.com',
    storageBucket: 'flutterapplic-c99bc.firebasestorage.app',
  );
}
